name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: 'Run Scalafmt'
        run: sbt -v ++3.7.2 scalafmtSbtCheck scalafmtCheckAll
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { scala: '3.3.0', java: '20', project: 'JVM' }
          - { scala: '3.7.2', java: '21', project: 'JVM' }
          - { scala: '3.7.2', java: '21', project: 'Native' }
    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: 'Run nativeLink'
        if: matrix.project == 'Native'
        run: sbt '++ ${{ matrix.scala }}' \
             acl4s${{ matrix.project }}/Test/nativeLink \
             example${{ matrix.project }}/Test/nativeLink
      - name: 'Run tests'
        run: sbt -v '++${{ matrix.scala }}' \
             acl4s${{ matrix.project }}/test \
             example${{ matrix.project }}/test
