name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        name: [ "test" ]
        scala: [ 3.3.0, 3.4.1 ]
        java: [ 20, 21 ]
        include:
          - name: "format"
            scala: 3.4.1
            java: 21
        exclude:
          - name: "test"
            scala: 3.3.0
            java: 21
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt
      - shell: bash
        run: |
          case ${{ matrix.name }} in
            "format")
              sbt -v ++${{ matrix.scala }} scalafmtSbt scalafmtAll
              git diff --exit-code
              ;;
            "test")
              sbt -v ++${{ matrix.scala }} test
              ;;
            *)
              echo "unknown job"
              exit 1
          esac
